# This is a basic workflow to help you get started with Actions

name: build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: wagoid/commitlint-github-action@v6.1.2
      - uses: bufbuild/buf-setup-action@v1.47.2
