# This is a basic workflow to help you get started with Actions

name: build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - uses: wagoid/commitlint-github-action@v5.4.5
      - uses: bufbuild/buf-setup-action@v1.29.0
