# This is a basic workflow to help you get started with Actions

name: build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: wagoid/commitlint-github-action@v5.5.1
      - uses: bufbuild/buf-setup-action@v1.29.0
