# This is a basic workflow to help you get started with Actions

name: PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: wagoid/commitlint-github-action@v5.4.5
      - uses: bufbuild/buf-setup-action@v1.26.1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          # The 'main' branch of the GitHub repository that defines the module.
          against: 'https://github.com/chief-of-state/chief-of-state-protos.git#branch=main'